INSERT INTO "Users"("Id", "Username", "Email", "Password", "Avatar")
VALUES
(1, 'okej', 'Okeej', 'Okeej', 'Vazi'),
(2, 'makisha', 'email', 'makisha', 'avatar'),
(3, 'nalog', 'email', 'password', 'avatar'),
(4, 'fake', 'email', 'password', 'avatar'),
(5, 'vazi', 'email', 'password', 'avatar'),
(6, 'lol', 'email', 'password', 'avatar'),
(7, 'wow', 'email', 'password', 'avatar'),
(8, 'party', 'email', 'password', 'avatar'),
(9, 'zurka', 'email', 'password', 'avatar'),
(10, 'lego', 'email', 'password', 'avatar'),
(11, 'taskEdit', 'email', 'password', 'avatar'),
(12, 'pwUpdateTest', 'pwUpdateTest@gmail.com', 'pwUpdateTest123@', 'avatar'),
(13, 'pwLoginTest', 'pwLoginTest@gmail.com', 'pwLoginTest123@', 'avatar'),
(14, 'pwVisitTest', 'pwVisitTest@gmail.com', 'pwVisitTest123@', 'avatar'),
(15, 'pwCreatePartyTest', 'pwCreatePartyTest@gmail.com', 'pwCreatePartyTest123@', 'avatar'),
(16, 'pwCancelPartyTest', 'pwCancelPartyTest@gmail.com', 'pwCancelPartyTest123@', 'avatar'),
(17, 'pwEditPartyTest', 'pwEditPartyTest@gmail.com', 'pwEditPartyTest123@', 'avatar'),
(18, 'pwAttendPartyTest', 'pwAttendPartyTest@gmail.com', 'pwAttendPartyTest123@', 'avatar'),
(19, 'pwUnattendPartyTest', 'pwUnattendPartyTest@gmail.com', 'pwUnattendPartyTest123@', 'avatar'),
(20, 'pwTaskCreateTest', 'pwTaskCreateTest@gmail.com', 'pwTaskCreateTest123@', 'avatar'),
(21, 'pwTaskEditTest', 'pwTaskEditTest@gmail.com', 'pwTaskEditTest123@', 'avatar'),
(22, 'pwTaskRemoveTest', 'pwTaskRemoveTest@gmail.com', 'pwTaskRemoveTest123@', 'avatar');